// <auto-generated />
using Infrastructure.SQLite;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Infrastructure.Migrations
{
    [DbContext(typeof(CSGOContext))]
    partial class CSGOContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1");

            modelBuilder.Entity("Core.Entities.Weapon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AmmoReserve")
                        .HasColumnType("INTEGER");

                    b.Property<double>("ArmorPenetration")
                        .HasColumnType("REAL");

                    b.Property<int>("BulletRange")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Bullets")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Damage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DamageFalloff")
                        .HasColumnType("TEXT");

                    b.Property<double>("FireRate")
                        .HasColumnType("REAL");

                    b.Property<string>("HoldToShoot")
                        .HasColumnType("TEXT");

                    b.Property<int>("KillAward")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MagazineSize")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mobility")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PenetrationPower")
                        .HasColumnType("TEXT");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TaggingPower")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tracers")
                        .HasColumnType("TEXT");

                    b.Property<string>("WeaponName")
                        .HasColumnType("TEXT");

                    b.Property<string>("WeaponType")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Weapons");
                });
#pragma warning restore 612, 618
        }
    }
}
